title: PRASHANTH SREEPATHI
logo: /assets/img/logo.jpg
description: Portfolio website for Prashanth Sreepathi.
show_downloads: true
theme: jekyll-theme-minimal
email: iamsreepathi@gmail.com
phone: 6059007958
resume: https://s3.us-east-2.amazonaws.com/resume.buildwithcode.dev/resume.pdf

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/ReddyPrashanth
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/prashanth-sreepathi-79a891188

navigation:
  - name: Introduction
    link: ./#introduction
  - name: Work Experience
    link: ./#work-experience
  - name: Education
    link: ./#education
  - name: Skills
    link: ./#skills
  - name: Projects
    link: ./#projects
  - name: Certifications
    link: ./#certifications
  - name: Awards
    link: ./#awards
  - name: Articles
    link: ./#articles
  - name: Code Repositories
    link: ./#code-repositories
